lib/plate_slate_web/router.ex
# ---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
# ---
defmodule PlateSlateWeb.Router do
  use PlateSlateWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(PlateSlateWeb.Context)
  end

  pipeline :admin_auth do
    plug(PlateSlateWeb.AdminAuth)
  end

  scope "/admin", PlateSlateWeb do
    pipe_through(:browser)

    resources("/session", SessionController, only: [:new, :create, :delete], singleton: true)
  end

  scope "/admin", PlateSlateWeb do
    pipe_through([:browser, :admin_auth])

    resources("/items", ItemController)
  end

  scope "/api" do
    pipe_through(:api)

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: PlateSlateWeb.Schema,
      # interface: :simple,
      socket: PlateSlateWeb.UserSocket
    )

    forward("/", Absinthe.Plug, schema: PlateSlateWeb.Schema)
  end
end

lib/plate_slate/menu/item.ex
# ---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
# ---
defmodule PlateSlate.Menu.Item do
  use Ecto.Schema
  import Ecto.Changeset
  alias PlateSlate.Menu.Item

  schema "items" do
    field :added_on, :date
    field :description, :string
    field :name, :string
    field :price, :decimal
    field :allergy_info, {:array, :map}

    belongs_to(:category, PlateSlate.Menu.Category)

    many_to_many(:tags, PlateSlate.Menu.ItemTag, join_through: "items_taggings")

    timestamps()
  end

  @doc false
  def changeset(%Item{} = item, attrs) do
    item
    |> cast(attrs, [:name, :description, :price, :added_on])
    |> validate_required([:name, :price])
    |> foreign_key_constraint(:category)
    |> unique_constraint(:name)
  end
end

lib/plate_slate/ordering/item.ex
defmodule PlateSlate.Ordering.Item do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :price, :decimal
    field :name, :string
    field :quantity, :integer
  end

  def changeset(item, attrs) do
    item
    |> cast(attrs, [:price, :name, :quantity])
    |> validate_required([:price, :name, :quantity])
  end
end

lib/plate_slate_web/controllers/item_controller.ex
defmodule PlateSlateWeb.ItemController do
  use PlateSlateWeb, :controller
  use Absinthe.Phoenix.Controller, schema: PlateSlateWeb.Schema, action: [mode: :internal]

  @graphql """
    query Index @action(mode: INTERNAL) {
      menu_items @put {
        category
        order_history {
          quantity
        }
      }
    }
  """
  def index(conn, result) do
    IO.inspect(result)
    render(conn, "index.html", items: result.data.menu_items || [])
  end

  @graphql """
  query ($id: ID!, $since: Date) {
    menu_item (id: $id) @put {
      order_history(since: $since) {
        quantity
        gross
        orders
      }
    }
  }
  """
  def show(conn, %{data: %{menu_item: nil}}) do
    conn
    |> put_flash(:info, "Menu item not found")
    |> redirect(to: "/admin/items")
  end

  def show(conn, %{data: %{menu_item: item}}) do
    since = variables(conn)["since"] || "2018-01-01"
    render(conn, "show.html", item: item, since: since)
  end
end

lib/plate_slate_web/views/item_view.ex
defmodule PlateSlateWeb.ItemView do
  use PlateSlateWeb, :view
end

lib/plate_slate_web/templates/item/edit.html.eex
<h2>Edit Item</h2>

<%= render "form.html", Map.put(assigns, :action, item_path(@conn, :update, @item)) %>

<span><%= link "Back", to: item_path(@conn, :index) %></span>

lib/plate_slate_web/templates/item/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/plate_slate_web/templates/item/index.html.eex
<h2>Listing Items</h2>

<table class="table">
  <thead>
    <tr>
      <th>Menu Item</th>
      <th>Category</th>
      <th>Quantity</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for item <- @items do %>
    <tr>
      <td><span><%= item.name %></span></td>
      <td><span><%= item.category.name %></span></td>
      <td><span><%= item.order_history.quantity %></span></td>
      <td class="text-right">
        <span><%= link "Show", to: item_path(@conn, :show, item), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: item_path(@conn, :edit, item), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: item_path(@conn, :delete, item), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Item", to: item_path(@conn, :new) %></span>

lib/plate_slate_web/templates/item/new.html.eex
<h2>New Item</h2>

<%= render "form.html", Map.put(assigns, :action, item_path(@conn, :create)) %>

<span><%= link "Back", to: item_path(@conn, :index) %></span>

lib/plate_slate_web/templates/item/show.html.eex
<h2><%= @item.name %></h2>

<%= form_tag item_path(@conn, :show, @item), method: :get do %>
    <div class="form-group">
        <label for="since">Since</label>
        <input type="date" id="since" name="since" value="<%= @since%>"  />
    </div>
    <%= submit "Filter Orders", class: "btn btn-primary" %>
<% end %>

<%= if Enum.empty?(@item.order_history.orders) do %>
    <p>No unit have been sold during this time period</p>
<% else %>
    <h3>Sold <%= @item.order_history.quantity %> (<%= Decimal.round(@item.order_history.gross, 2) %> gross)</h3>

<table class="table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Count</th>
        </tr>
    </thead>
    <tboby>
        <%= for order <- @item.order_history.orders do %>
            <tr>
                <td><%= order.ordered_at |> DateTime.to_date() %></td>
                <td><%= order.items |> Enum.map(& &1.quantity) |> Enum.sum() %></td>
            </tr>

        <% end %>

    </tboby>
</table>
<% end %>
<span><%= link "Back", to: item_path(@conn, :index), class: "btn btn-default btn-xs" %></span>